Import("env")
import os, sys

model_path = os.path.join(env.subst("$PROJECT_DIR"), "models", "knn_model.json")
out_path   = os.path.join(env.subst("$PROJECT_DIR"), "src",    "knn_model_embed.h")

if not os.path.isfile(model_path):
    print("ERROR: KNN_MODEL_EMBED defined but models/knn_model.json not found")
    sys.exit(1)

with open(model_path, "rb") as fh:
    data = fh.read()

print("  [embed_knn] {:d} bytes from models/knn_model.json".format(len(data)))

with open(out_path, "w", newline="\n") as fh:
    fh.write("// Auto-generated by embed_knn_model.py -- do not edit\n")
    fh.write("static const uint32_t KNN_MODEL_EMBED_LEN = {:d}u;\n".format(len(data)))
    fh.write("static const uint8_t  KNN_MODEL_EMBED[] = {{\n")
    for i, b in enumerate(data):
        fh.write("0x{:02x},".format(b))
        if (i + 1) % 16 == 0:
            fh.write("\n")
    fh.write("\n}};\n")
